spring:
  datasource:
    username: root
    password: 654123
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/scientific_research?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true

  aop:
    proxy-target-class: true
    auto: true

  thymeleaf:
    cache: false

  #tomcat的默认设置限制了上传的文件大小为1MB
  #修改最大上传文件为20MB，最大总请求数据大小为200MB
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/hao/scientficresearch/mapper/**/*.xml

logging:
  level:
    root: info
    com.hao.scientiticresearch: info
  file:
    name: scientificresearch/log/log.log


