spring:
  datasource:
    username: root
    password: 654123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置数据库
    url: jdbc:mysql://localhost:3306/scientific_research?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
  # 启用切面
  aop:
    proxy-target-class: true
    auto: true

  thymeleaf:
    cache: false

  #tomcat的默认设置限制了上传的文件大小为1MB
  #修改最大上传文件为20MB，最大总请求数据大小为200MB
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
# 配置发送隐藏方法，即通过表单发送put,delete请求
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
# MP配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/hao/scientficresearch/mapper/**/*.xml
# 日志配置
logging:
  level:
    root: info
    com.hao.scientiticresearch: info
  file:
    name: scientificresearch/log/log.log
#  pattern:
#    file: %d{yyyy-MM-dd HH:mm:ss.SSS} === %-5level === [%thread] === %logger{50} ----- %msg%n

